export { BEFORE_REQUEST, REQUESTING, REQUEST_FAILURE, REQUEST_ERROR, REQUEST_OK }

const BEFORE_REQUEST = 0;
const REQUESTING = 1;
const REQUEST_FAILURE = 2;
const REQUEST_ERROR = 3;
const REQUEST_OK = 4;